CARDS
-----
insert into ORC_OUTPUT_AGGREGATION (BATCH_INSTANCE_ID,SCHEDULE_ID,REPORTING_PERIOD,PRODUCT_TYPE,REGION,AGE,CURR_DLQ_STATUS,ORIG_FICO,N_ACCT,D_UPB,D_ENR,D_OS_ACCT_GE30_DPD_24M,N_ACCTS_GE30_DPD_24M,N_NEW_ACCOUNTS,D_COMMITMENTS,D_NEW_COMMITMENTS,D_GROSS_CONTRACTUAL_CO,D_BANKRUPTCY_CO,D_RECOVERIES,N_ACCT_CO,D_NET_CO,D_ADJ_NET_CO) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)

MORTGAGE
--------
insert into ORC_OUTPUT_AGGREGATION (BATCH_INSTANCE_ID,SCHEDULE_ID,REPORTING_PERIOD,PRODUCT_TYPE,REGION,ORIG_LTV,AGE,CURR_DLQ_STATUS,ORIG_FICO,N_ACCT,D_UPB,D_ENR,N_NEW_ACCOUNTS,D_GROSS_CONTRACTUAL_CO,D_BANKRUPTCY_CO,D_RECOVERIES,N_ACCT_CO,D_NET_CO,D_ADJ_NET_CO) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)

HOMEEQUITY
-----------
insert into ORC_OUTPUT_AGGREGATION (BATCH_INSTANCE_ID,SCHEDULE_ID,REPORTING_PERIOD,PRODUCT_TYPE,REGION,ORIG_LTV,AGE,CURR_DLQ_STATUS,ORIG_FICO,N_ACCT,D_UPB,D_ENR,N_NEW_ACCOUNTS,D_NEW_ACCOUNTS,D_COMMITMENTS,D_NEW_COMMITMENTS,D_COMMITMENT_INCREASES,D_COMMITMENT_DECREASES,D_GROSS_CONTRACTUAL_CO,D_BANKRUPTCY_CO,D_RECOVERIES,N_ACCT_CO,D_NET_CO,D_ADJ_NET_CO,D_FORECLOSURE,D_NEW_FORECLOSURE,D_REO,D_NEW_REO) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)

INTL SMALL BUSINESS
--------------------

insert into ORC_OUTPUT_AGGREGATION (BATCH_INSTANCE_ID,SCHEDULE_ID,REPORTING_PERIOD,PRODUCT_TYPE,REGION,AGE,CURR_DLQ_STATUS,ORIG_FICO,N_ACCT,D_UPB,D_ENR,N_NEW_ACCOUNTS,D_COMMITMENTS,D_MODIFICATIONS,D_GROSS_CONTRACTUAL_CO,D_BANKRUPTCY_CO,D_RECOVERIES,N_ACCT_CO,D_NET_CO,D_ADJ_NET_CO) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)


US SMALL BUSINESS
------------------

insert into ORC_OUTPUT_AGGREGATION (BATCH_INSTANCE_ID,SCHEDULE_ID,REPORTING_PERIOD,PRODUCT_TYPE,AGE,CURR_DLQ_STATUS,ORIG_FICO,N_ACCT,D_UPB,D_ENR,N_NEW_ACCOUNTS,D_COMMITMENTS,D_MODIFICATIONS,D_GROSS_CONTRACTUAL_CO,D_BANKRUPTCY_CO,D_RECOVERIES,N_ACCT_CO,D_NET_CO,D_ADJ_NET_CO) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)


INTL OTHER CONSUMER
-------------------
insert into ORC_OUTPUT_AGGREGATION (BATCH_INSTANCE_ID,SCHEDULE_ID,REPORTING_PERIOD,PRODUCT_TYPE,REGION,ORIG_LTV,CURR_DLQ_STATUS,ORIG_FICO,N_ACCT,D_UPB,D_ENR,N_NEW_ACCOUNTS,D_NEW_COMMITMENTS,D_GROSS_CONTRACTUAL_CO,D_BANKRUPTCY_CO,D_RECOVERIES,N_ACCT_CO,D_NET_CO,D_ADJ_NET_CO) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)


US OTHER CONSUMER
-----------------

insert into ORC_OUTPUT_AGGREGATION (BATCH_INSTANCE_ID,SCHEDULE_ID,REPORTING_PERIOD,PRODUCT_TYPE,ORIG_LTV,CURR_DLQ_STATUS,ORIG_FICO,N_ACCT,D_UPB,D_ENR,N_NEW_ACCOUNTS,D_NEW_COMMITMENTS,D_GROSS_CONTRACTUAL_CO,D_BANKRUPTCY_CO,D_RECOVERIES,N_ACCT_CO,D_NET_CO,D_ADJ_NET_CO) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)