package com.citi.retail.optima.etl.common;

public interface ETLLoggingConstants {

	String CARDS_OBJECT = "CARDS_OBJECT";
	String BATCH_DETAILS_OBJECT = "BATCH_DETAILS_OBJECT";
	String JOB_EXECUTION = "JOB_EXECUTION";
	String STEP_EXECUTION = "STEP_EXECUTION";
	String INCOMING_MESSAGE = "INCOMING_MESSAGE";
	String AGGREGATION_RULES = "AGGREGATION_RULES";
	String ENRICHMENT_RULES = "ENRICHMENT_RULES";
	String JOB_STATUS_AT_START = "JOB_STATUS_AT_START";
	String BATCH_NAME = "BATCH_NAME";
	String ORG_MSG_ID_BATCH = "ORG_MSG_ID_BATCH";
	String BATCH_RECVD_EVENT_TIMESTAMP = "BATCH_RECVD_EVENT_TIMESTAMP";
	String BATCH_PARAMETERS = "BATCH_PARAMETERS";
	String STEP_MAX_KEY = "STEP_MAX_KEY";
	String STEP_MIN_KEY = "STEP_MIN_KEY'";
	String REPORT_DATE = "REPORT_DATE";
	String PORTFOLIO_ID = "PORTFOLIO_ID";
	String PROCESS_UNIT_LIST = "PROCESS_UNIT_LIST";
	String PRODUCT_LIST = "PRODUCT_LIST";
	String COMMA_STRING = " , ";

	// CONTROLER LOGGING CONSTANTS

	String CONTROLLER_PROD_LIST = "CONTROLLER_PROD_LIST";
	String CONTROLLER_CNTRY_CODE = "CONTROLLER_CNTRY_CODE";
	String CONTROLLER_PFOLIO_ID = "CONTROLLER_PFOLIO_ID";
	String CONTROLLER_RETURN_BATCH_INST_ID = "CONTROLLER_RETURN_BATCH_INST_ID";
	String CONTROLLER_JOB_INST_CRTE = "CONTROLLER_JOB_INST_CRTE";

}
