package com.citi.retail.optima.etl.batch.job.mapper;

import org.springframework.batch.item.file.mapping.FieldSetMapper;
import org.springframework.batch.item.file.transform.FieldSet;
import org.springframework.validation.BindException;

import com.citi.retail.optima.etl.common.log.LoggingMarker;
import com.citi.retail.optima.etl.common.model.TwRcPostRainbowRecord;
import com.citi.retail.optima.etl.common.model.TwRcPreRainbowRecord;

public class TwRcPreRainbowFieldSetMapper extends AbstractFieldSetMapper implements FieldSetMapper{

	public TwRcPreRainbowRecord mapFieldSet(FieldSet fieldSet) throws BindException {
		/*TwRcPostRainbowRecord record = new TwRcPostRainbowRecord();
		record.setAcctActivationDt(readInt(fieldSet,"acctActivationDt"));
		record.setAcctIntrnlStatCde(fieldSet.readString("acctIntrnlStatCde"));
		record.setAcctOpenDt(readDate(fieldSet,"acctOpenDt"));
		record.setAcctPrimBlkCde(fieldSet.readString("acctPrimBlkCde"));
		record.setAcctPrimBlkDt(readDate(fieldSet,"acctPrimBlkDt"));
		record.setAcctRskLvl(fieldSet.readString("acctRskLvl"));
		record.setAgntCde(fieldSet.readString("agntCde"));
		record.setCashIbnp(readDouble(fieldSet,"cashIbnp"));
		record.setCashSvcBnp(readDouble(fieldSet,"cashSvcBnp"));
		record.setCclInd(fieldSet.readString("cclInd"));
		record.setChrgOffLcyamt(readDouble(fieldSet,"chrgOffLcyamt"));
		record.setClntBirthDt(readDate(fieldSet,"clntBirthDt"));
		record.setClntEcsOccpnCde(fieldSet.readString("clntEcsOccpnCde"));
		record.setClntResdStatCde(fieldSet.readString("clntResdStatCde"));
		record.setClntWorkIndustryCde(fieldSet.readString("clntWorkIndustryCde"));
		record.setCrdAcctNbr(fieldSet.readString("crdAcctNbr"));
		record.setCrdBlkCde(fieldSet.readString("crdBlkCde"));
		record.setCrdBlkCdeDt(readDate(fieldSet,"crdBlkCdeDt"));
		record.setCrdBlkRsn(fieldSet.readString("crdBlkRsn"));
		record.setCrdCncldDt(readDate(fieldSet,"crdCncldDt"));
		record.setCrdIssueDt(readDate(fieldSet,"crdIssueDt"));
		record.setCrdNbr(fieldSet.readString("crdNbr"));
		record.setCrdTyp(fieldSet.readString("crdTyp"));
		record.setCreationDt(readDate(fieldSet,"creationDt"));
		record.setCrlmRelnLcyamt(readInt(fieldSet,"crlmRelnLcyamt"));
		record.setCtlFlag(fieldSet.readString("ctlFlag"));
		record.setDelqStr(fieldSet.readString("delqStr"));
		record.setDirectDrInd(fieldSet.readString("directDrInd"));
		record.setEmvInd(fieldSet.readString("emvInd"));
		record.setLossMtgtnCnt(fieldSet.readString("lossMtgtnCnt"));
		record.setLstActyDt (readInt(fieldSet,"lstActyDt "));
		record.setNasSrcCde(fieldSet.readString("nasSrcCde"));
		record.setNbrOfSupCrds(readInt(fieldSet,"nbrOfSupCrds"));
		record.setPlsticIdCde(fieldSet.readString("plsticIdCde"));
		record.setPymtHstryStr(fieldSet.readString("pymtHstryStr"));
		record.setRelnNbr(fieldSet.readString("relnNbr"));
		record.setRtlIbnp(readDouble(fieldSet,"rtlIbnp"));
		record.setRtlInsurBnp(readInt(fieldSet,"rtlInsurBnp"));
		record.setRtlMemberBnp(readDouble(fieldSet,"rtlMemberBnp"));
		record.setRtlMiscBnp(readDouble(fieldSet,"rtlMiscBnp"));
		record.setRtlSvcBnp(readDouble(fieldSet,"rtlSvcBnp"));
		record.setAcctBlkRsn1Cyc(fieldSet.readString("acctBlkRsn1Cyc"));
		record.setAcctBlkRsn2Cyc(fieldSet.readString("acctBlkRsn2Cyc"));
		record.setAcctInd(fieldSet.readString("acctInd"));
		record.setAcctPrimBlkRsnCde(fieldSet.readString("acctPrimBlkRsnCde"));
		record.setAlopAmnt(readInt(fieldSet,"alopAmnt"));
		record.setAlopCrlimit(readDouble(fieldSet,"alopCrlimit"));
		record.setAnfee (readInt(fieldSet,"anfee "));
		record.setAnr2(readDouble(fieldSet,"anr2"));
		record.setBehscore(fieldSet.readString("behscore"));
		record.setBlock1(fieldSet.readString("block1"));
		record.setBscoreid(fieldSet.readString("bscoreid"));
		record.setBtintr(readInt(fieldSet,"btintr"));
		record.setCiRate(readInt(fieldSet,"ciRate"));
		record.setClntNbr(fieldSet.readString("clntNbr"));
		record.setClt1(readInt(fieldSet,"clt1"));
		record.setClt2(readDouble(fieldSet,"clt2"));
		record.setCshblnc2(readDouble(fieldSet,"cshblnc2"));
		record.setCshfee(readDouble(fieldSet,"cshfee"));
		record.setCshintr(readDouble(fieldSet,"cshintr"));
		record.setCurrDueAmt(readDouble(fieldSet,"currDueAmt"));
		record.setCurrblnc(readInt(fieldSet,"currblnc"));
		record.setCycle(readInt(fieldSet,"cycle"));
		record.setDatepay(readInt(fieldSet,"datepay"));
		record.setDelqprof(fieldSet.readString("delqprof"));
		record.setDwcpmTotalAmtDue(readInt(fieldSet,"dwcpmTotalAmtDue"));
		record.setEducation(fieldSet.readString("education"));
		record.setEnrLcyamt(readInt(fieldSet,"enrLcyamt"));
		record.setEppAmnt(readInt(fieldSet,"eppAmnt"));
		record.setGender(fieldSet.readString("gender"));
		record.setIdno(fieldSet.readString("idno"));
		record.setIncome(readInt(fieldSet,"income"));
		record.setLatefee(readDouble(fieldSet,"latefee"));
		record.setLcshamt2(readDouble(fieldSet,"lcshamt2"));
		record.setLcshcnt2(readInt(fieldSet,"lcshcnt2"));
		record.setLcycblnc(readInt(fieldSet,"lcycblnc"));
		record.setLrtlamt2(readDouble(fieldSet,"lrtlamt2"));
		record.setLrtlcnt2(readInt(fieldSet,"lrtlcnt2"));
		record.setMonblnc(readDouble(fieldSet,"monblnc"));
		record.setMue (readInt(fieldSet,"mue"));
		record.setNbalamt2(readInt(fieldSet,"nbalamt2 "));
		record.setOcshamt2(readDouble(fieldSet,"ocshamt2 "));
		record.setOcshcnt2(readInt(fieldSet,"ocshcnt2"));
		record.setOpenAcct(readInt(fieldSet,"openAcct"));
		record.setOpenCif(readInt(fieldSet,"openCif"));
		record.setOrtlamt2(readDouble(fieldSet,"ortlamt2"));
		record.setOrtlcnt2(readInt(fieldSet,"ortlcnt2"));
		record.setOtherfee(readInt(fieldSet,"otherfee"));
		record.setOvrlmtExclsnInd(fieldSet.readString("ovrlmtExclsnInd"));
		record.setPast30Amt(readInt(fieldSet,"past30Amt"));
		record.setPastDueAmt(readDouble(fieldSet,"pastDueAmt  "));
		record.setPayamt1(readInt(fieldSet,"payamt1"));
		record.setPayamt2(readInt(fieldSet,"payamt2"));
		record.setReanr(readInt(fieldSet,"reanr"));
		record.setRiRate(readInt(fieldSet,"riRate"));
		record.setRtlintr(readDouble(fieldSet,"rtlintr"));
		record.setStatus1(fieldSet.readString("status1"));
		record.setTotAcct(readInt(fieldSet,"totAcct"));
		record.setTte(readInt(fieldSet,"tte"));
		record.setUsercde3(fieldSet.readString("usercde3"));*/
		
		TwRcPreRainbowRecord record = new TwRcPreRainbowRecord();
		
		record.setAcctind(fieldSet.readString("acctind"));
		record.setAgencode(fieldSet.readString("agencode"));
		record.setAlopAmnt(readInt(fieldSet,"alopAmnt"));
		record.setAlopCrlimit(readDouble(fieldSet,"alopCrlimit"));
		record.setAlopOldCrlimit(readInt(fieldSet,"alopOldCrlimit"));
		record.setAlopSpLmtPer(readInt(fieldSet,"alopSpLmtPer"));
		record.setAlopTotlimit(readInt(fieldSet,"alopTotlimit"));
		record.setAltblk1(fieldSet.readString("altblk1"));
		record.setAltblk2(fieldSet.readString("altblk2"));
		record.setAnfee(readDouble(fieldSet,"anfee"));
		record.setAnr1(readInt(fieldSet,"anr1"));
		record.setAnr2(readDouble(fieldSet,"anr2"));
		record.setBar(readInt(fieldSet,"bar"));
		record.setBehscore(readInt(fieldSet,"behscore"));
		record.setBlock1(fieldSet.readString("block1"));
		record.setBlock2(fieldSet.readString("block2"));
		record.setBs12M(readInt(fieldSet,"bs12M"));
		record.setBs6M(readInt(fieldSet,"bs6M"));
		record.setBscoreid(readInt(fieldSet,"bscoreid"));
		record.setBsid12M(readInt(fieldSet,"bsid12M"));
		record.setBsid6M(readInt(fieldSet,"bsid6M"));
		record.setCardnmbr(fieldSet.readString("cardnmbr"));
		record.setCardtype(fieldSet.readString("cardtype"));
		record.setCbr(readInt(fieldSet,"cbr"));
		record.setClscod1(fieldSet.readString("clscod1"));
		record.setClscod2(fieldSet.readString("clscod2"));
		record.setClt1(readInt(fieldSet,"clt1"));
		record.setClt2(readDouble(fieldSet,"clt2"));
		record.setCnr(readInt(fieldSet,"cnr"));
		record.setCoffamt(readInt(fieldSet,"coffamt"));
		record.setCshblnc1(readInt(fieldSet,"cshblnc1"));
		record.setCshblnc2(readInt(fieldSet,"cshblnc2"));
		record.setCshfee(readDouble(fieldSet,"cshfee"));
		record.setCshintr(readDouble(fieldSet,"cshintr"));
		record.setCurrblnc(readInt(fieldSet,"currblnc"));
		record.setCurrLscode(fieldSet.readString("currLscode"));
		record.setCurrLscodeEffDte(readInt(fieldSet,"currLscodeEffDte"));
		record.setCustid(fieldSet.readString("custid"));
		record.setCycle(readInt(fieldSet,"cycle"));
		record.setDateblk1(readDate(fieldSet,"dateblk1"));
		record.setDateblk2(readDate(fieldSet,"dateblk2"));
		//record.setDatebrth(fieldSet.readString("datebrth"));
		record.setDateclt1(readDate(fieldSet,"dateclt1"));
		record.setDateclt2(readDate(fieldSet,"dateclt2"));
		record.setDatecncl(readDate(fieldSet,"datecncl"));
		record.setDatecsh(readDate(fieldSet,"datecsh"));
		record.setDateexp1(readDate(fieldSet,"dateexp1"));
		record.setDateexp2(readDate(fieldSet,"dateexp2"));
		record.setDatefee(readDate(fieldSet,"datefee"));
		record.setDateopen(readDate(fieldSet,"dateopen"));
		record.setDatepay(readDate(fieldSet,"datepay"));
		record.setDatertl(readDate(fieldSet,"datertl"));
		record.setDatest1(readDate(fieldSet,"datest1"));
		record.setDatest2(readDate(fieldSet,"datest2"));
		record.setDatetmpf(readDate(fieldSet,"datetmpf"));
		record.setDatetmpt(readDate(fieldSet,"datetmpt"));
		record.setDatlclt1(readDate(fieldSet,"datlclt1"));
		record.setDatlclt2(readDate(fieldSet,"datlclt2"));
		record.setDcnt1(readInt(fieldSet,"dcnt1"));
		record.setDcnt2(readInt(fieldSet,"dcnt2"));
		record.setDcnt3(readInt(fieldSet,"dcnt3"));
		record.setDcnt4(readInt(fieldSet,"dcnt4"));
		record.setDcnt5(readInt(fieldSet,"dcnt5"));
		record.setDcnt6(readInt(fieldSet,"dcnt6"));
		record.setDcnt7(readInt(fieldSet,"dcnt7"));
		record.setDcnt8(readInt(fieldSet,"dcnt8"));
		record.setDelqprof(fieldSet.readString("delqprof"));
		record.setDevncode(fieldSet.readString("devncode"));
		record.setDuedategrp(fieldSet.readString("duedategrp"));
		record.setEduction(fieldSet.readString("eduction"));
		record.setEmvCardUseInd(fieldSet.readString("emvCardUseInd"));
		record.setEmvTag(fieldSet.readString("emvTag"));
		record.setEppAmnt(readDouble(fieldSet,"eppAmnt"));
		record.setFeecode(fieldSet.readString("feecode"));
		record.setFinChrg(readInt(fieldSet,"finChrg"));
		record.setGender(fieldSet.readString("gender"));
		record.setHometime(readInt(fieldSet,"hometime"));
		record.setHomezip(fieldSet.readString("homezip"));
		record.setHsowner(fieldSet.readString("hsowner"));
		record.setIdno(fieldSet.readString("idno"));
		record.setIncome(readInt(fieldSet,"income"));
		record.setIntrst(readInt(fieldSet,"intrst"));
		record.setJcicIcno(fieldSet.readString("jcicIcno"));
		record.setJcicSi(fieldSet.readString("jcicSi"));
		record.setLatefee(readDouble(fieldSet,"latefee"));
		record.setLbehscor(readInt(fieldSet,"lbehscor"));
		record.setLbscorid(readInt(fieldSet,"lbscorid"));
		record.setLclscod1(fieldSet.readString("lclscod1"));
		record.setLclscod2(fieldSet.readString("lclscod2"));
		record.setLclt1(readInt(fieldSet,"lclt1"));
		record.setLclt2(readInt(fieldSet,"lclt2"));
		record.setLcshamt1(readInt(fieldSet,"lcshamt1"));
		record.setLcshamt2(readDouble(fieldSet,"lcshamt2"));
		record.setLcshcnt1(readInt(fieldSet,"lcshcnt1"));
		record.setLcshcnt2(readInt(fieldSet,"lcshcnt2"));
		record.setLcycblnc(readInt(fieldSet,"lcycblnc"));
		record.setLmonblnc(readInt(fieldSet,"lmonblnc"));
		record.setLrtlamt1(readInt(fieldSet,"lrtlamt1"));
		record.setLrtlamt2(readDouble(fieldSet,"lrtlamt2"));
		record.setLrtlcnt1(readInt(fieldSet,"lrtlcnt1"));
		record.setLrtlcnt2(readInt(fieldSet,"lrtlcnt2"));
		record.setMarriage(fieldSet.readString("marriage"));
		record.setMonblnc(readDouble(fieldSet,"monblnc"));
		record.setMdue(readDouble(fieldSet,"mdue"));
		record.setOccupatn(fieldSet.readString("occupatn"));
		record.setOcshamt1(readInt(fieldSet,"ocshamt1"));
		record.setOcshamt2(readDouble(fieldSet,"ocshamt2"));
		record.setOcshcnt1(readInt(fieldSet,"ocshcnt1"));
		record.setOcshcnt2(readInt(fieldSet,"ocshcnt2"));
		record.setOrtlamt1(readInt(fieldSet,"ortlamt1"));
		record.setOrtlamt2(readDouble(fieldSet,"ortlamt2"));
		record.setOrtlcnt1(readInt(fieldSet,"ortlcnt1"));
		record.setOrtlcnt2(readInt(fieldSet,"ortlcnt2"));
		record.setOtherfee(readDouble(fieldSet,"otherfee"));
		record.setPayamt1(readInt(fieldSet,"payamt1"));
		record.setPayamt2(readInt(fieldSet,"payamt2"));
		record.setPendLscode(fieldSet.readString("pendLscode"));
		record.setPhoto(fieldSet.readString("photo"));
		record.setPot(readInt(fieldSet,"pot"));
		record.setPotexp(readInt(fieldSet,"potexp"));
		record.setPrevLscode(fieldSet.readString("prevLscode"));
		record.setProfessn(fieldSet.readString("professn"));
		record.setReagedate1(readInt(fieldSet,"reagedate1"));
		record.setReagedate2(readInt(fieldSet,"reagedate2"));
		record.setReagereq1(fieldSet.readString("reagereq1"));
		record.setReagereq2(fieldSet.readString("reagereq2"));
		record.setRecIntr(readInt(fieldSet,"recIntr"));
		record.setRecOth(readInt(fieldSet,"recOth"));
		record.setRecPrn(readInt(fieldSet,"recPrn"));
		record.setRevind(fieldSet.readString("revind"));
		record.setRisklevl(fieldSet.readString("risklevl"));
		record.setRtlblnc1(readInt(fieldSet,"rtlblnc1"));
		record.setRtlblnc2(readInt(fieldSet,"rtlblnc2"));
		record.setRtlintr(readDouble(fieldSet,"rtlintr"));
		record.setScore(readInt(fieldSet,"score"));
		record.setScoreid(readInt(fieldSet,"scoreid"));
		record.setSource(fieldSet.readString("source"));
		record.setStatus1(fieldSet.readString("status1"));
		record.setStatus2(fieldSet.readString("status2"));
		record.setSuppcard(readInt(fieldSet,"suppcard"));
		record.setTempclt(readInt(fieldSet,"tempclt"));
		record.setTempind(fieldSet.readString("tempind"));
		record.setTotAmtDue(readInt(fieldSet,"totAmtDue"));
		record.setWorkzip(fieldSet.readString("workzip"));
		record.setWoIntr(readInt(fieldSet,"woIntr"));
		record.setWoOther(readInt(fieldSet,"woOther"));
		record.setWoPrn(readInt(fieldSet,"woPrn"));
		record.setAchind(fieldSet.readString("achind"));
		record.setAddressChgDte(readInt(fieldSet,"addressChgDte"));
		record.setAvailclt(readInt(fieldSet,"availclt"));
		record.setAvaline(readInt(fieldSet,"avaline"));
		record.setCashAccrIntr(readDouble(fieldSet,"cashAccrIntr"));
		record.setCiRate(readDouble(fieldSet,"ciRate"));
		record.setCreScor(readInt(fieldSet,"creScor"));
		record.setCreatdte(readInt(fieldSet,"creatdte"));
		record.setEbOinc(readInt(fieldSet,"ebOinc"));
		record.setIncInd (fieldSet.readString("incInd"));
		record.setMemberSinceDate(readInt(fieldSet,"memberSinceDate"));
		record.setMue(readInt(fieldSet,"mue"));
		record.setOincInd(fieldSet.readString("oincInd"));
		record.setPinregen(readInt(fieldSet,"pinregen"));
		record.setRevScor(readInt(fieldSet,"revScor"));
		record.setRiRate(readDouble(fieldSet,"riRate"));
		record.setRtlAccrIntr(readDouble(fieldSet,"rtlAccrIntr"));
		record.setScoreId(fieldSet.readString("scoreid"));
		record.setTte(readInt(fieldSet,"tte"));
		record.setUsercde1(fieldSet.readString("usercde1"));
		record.setUsercde2(fieldSet.readString("usercde2"));
		record.setUsercde3(fieldSet.readString("usercde3"));
		record.setXferEff(readInt(fieldSet,"xferEff"));
		record.setzType(fieldSet.readString("zType"));
		record.setUsercde3(fieldSet.readString("usercde3"));
		record.setGcbcPortfolioId(fieldSet.readString("gcbcPortfolioId"));
		record.setAlignScore(readInt(fieldSet,"alignScore"));
		/**For Logging
		 * 
		 */
		if(getExceptionList().size() > 0) {
			KPILOGGER.error(LoggingMarker.KPI.getMarker(), "ERROR Record: "+ record.toString());
			for(Exception e: getExceptionList()) {
				KPILOGGER.error(LoggingMarker.KPI.getMarker(), "ERROR DETAILS: "+e.getMessage());
			}
			getExceptionList().clear();
			KPILOGGER.error(LoggingMarker.KPI.getMarker(), "\n");
		}
		return record;
	}

}
