package com.citi.retail.optima.etl.controller.model;

/**
 * @author hs73849
 * 
 */
public enum RequestMessageType {
	GENESIS, MANUAL, NEW_REQUEST, BATCH_COMPLETION, CCAR_USER_SUBMISSION, FDIC_USER_SUBMISSION, GCBC_LLR_DATA, GCBC_PORTFOLIO_DEFINITION, PEARL_LLR_DATA, USER_LLR_DATA, WEB_MA_LLR_DATA, GC20_LLR_DATA,SUPPLEMENTARY_DATA,FVO_HFS_DATA, DATA_ACQUISITION
}
